#!/bin/sh
# Home Assistant distro setup script
#
# Copyright (c) 2022, Marc Kelly
# Copyright (c) 2020, Matthew Madison
# Poritions Copyright (C) 2006-2001 Linux Foundation
#
# SPDX-License-Identifier: GPL-2.0-or-later

#
# See scripts-setup/setup-env-internal for usage information.
# For shells that do not pass arguments to sourced scripts (e.g., dash),
# you can set MACHINE and DISTRO in your environment to appropriate
# values before sourcing this script.
#
#
# Initial boilerplate from the oe-init-build-env
if [ -n "$BASH_SOURCE" ]; then
    THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    THIS_SCRIPT=$0
else
    THIS_SCRIPT="$(pwd)/setup-env"
    if [ ! -e "$THIS_SCRIPT" ]; then
        echo "Error: $THIS_SCRIPT doesn't exist!" >&2
        echo "Please run this script in setup-env's directory." >&2
        return 1
    fi
fi

if [ -n "$BBSERVER" ]; then
    unset BBSERVER
fi

if [ -z "$ZSH_NAME" ] && [ "$0" = "$THIS_SCRIPT" ]; then
    echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'" >&2
    exit 1
fi

# Running bitbake builds as root can cause issues, so flag this

if [ $(id -u) -eq 0 ]; then
    echo "ERROR: do not use the BSP as root. Exiting..."
    unset THIS_SCRIPT
    return 1
fi

HA_TOP=$(dirname "$THIS_SCRIPT")
HA_TOP=$(readlink -f "$HA_TOP")
HA_SCRIPTDIR="$HA_TOP/scripts-setup"

# Automatically update the git submodules.  It's common to forget
# to do this after updating the main repository to latest.

"$HA_SCRIPTDIR/update-git-submodules" "$HA_TOP"

# We use HA_VARS to track the variables that need to
# be unset before exiting this script.
HA_RC=0
HA_VARS="HA_RC HA_SCRIPTDIR HA_TOP THIS_SCRIPT HA_VARS"

# Call on setup-env-internal to parse any arguments. It
# will emit variable assignments on stdout.
eval $(HA_TOP="$HA_TOP" "$HA_SCRIPTDIR/setup-env-internal" "$THIS_SCRIPT" "$@")
if [ $HA_RC -ne 0 ]; then
    for var in $(echo $HA_VARS); do unset $var; done; unset var
    return 1
fi

OEROOT=$(readlink -f "$HA_TOP/layers")
export OEROOT

# There can be multiple distro layers in the repository, which
# may require different setups.  The .templateconf file in the
# distro layer can be used to handle where to look for config
# templates.
if [ -n "$HA_NEEDSETUP" ]; then
    DISTRO="$HA_DISTRO"
    # If the layer directory has a .templateconf file, use that to set TEMPLATECONF
    if [ -e "$OEROOT/$HA_LAYERPATH/.templateconf" ]; then
	. "$OEROOT/$HA_LAYERPATH/.templateconf"
    fi
fi

# Now things are set up to let the OE setup scripts to their jobs
. $OEROOT/scripts/oe-buildenv-internal &&
    TEMPLATECONF="$TEMPLATECONF" $OEROOT/scripts/oe-setup-builddir || {
	for var in $(echo $HA_VARS OEROOT DISTRO TEMPLATECONF); do unset $var; done; unset var
	return 1
    }

# Make sure to configure in the user's distro and machine settings
# into local.conf if this is the first time setting up.
if [ -n "$HA_NEEDSETUP" ]; then
    unset DISTRO TEMPLATECONF
    echo "$HA_LAYERPATH" > "$BUILDDIR/conf/distrolayer.cfg"
    # Replace placeholder comments with default settings
    sed -e"/@HA_SETUP_MACHINE@/c \MACHINE ?= \"$HA_MACHINE\"" \
        -e"/@HA_SETUP_DISTRO@/c \DISTRO ?= \"$HA_DISTRO\"" -i "$BUILDDIR/conf/local.conf"
    cat <<EOF

Your build environment has been configured with:
    MACHINE=$HA_MACHINE
    DISTRO=$HA_DISTRO
    $devnet_info__
EOF
    for s__ in .oe/$HA_DISTRO .yocto/$HA_DISTRO .oe .yocto ; do
        if [ -e "$HOME/$s__/site.conf" ]; then
            echo "Linking $s__/site.conf to conf/site.conf"
            ln -sf "$HOME/$s__/site.conf" "$BUILDDIR/conf/"
        fi
    done
    unset devnet_info__ s__
else
    HA_LAYERPATH=$(cat "$BUILDDIR/conf/distrolayer.cfg")
    TEMPLATECONF=$(cat "$BUILDDIR/conf/templateconf.cfg") COLOR=$HA_COLOR "$HA_TOP/scripts-setup/diff-bblayers-conf"
fi

# Add the distro layer's scripts directory to PATH and
# source its environment setup script, if present
if [ -d "$OEROOT/$HA_LAYERPATH/scripts" ]; then
    PATH="$OEROOT/$HA_LAYERPATH/scripts:$PATH"
    if [ -e "$OEROOT/$HA_LAYERPATH/scripts/layer-setup-env" ]; then
        . "$OEROOT/$HA_LAYERPATH/scripts/layer-setup-env"
    fi
fi

# Generally don't want world-writable output by default
# for builds, so fix the umask if it's set that way.
if [ "`umask | tail -c 2`" = "7" ]; then
    umask 0022
fi
for var in $(echo $HA_VARS OEROOT); do unset $var; done; unset var

[ -z "$BUILDDIR" ] || cd "$BUILDDIR"
